### ISSUE TITLE
Are you accepting pull requests?

### ISSUE THREAD

**Issue by addisonamiri** [jdkanani/vim-material-theme#7]
I already sent one to you for the name of the colorscheme and I had another to hide the end-of-file tildes that vim adds. Neovim has a feature that allows you to hide them so I introduced a variable that allows a user to hide them if they want to. If you'll accept it I'll add it to my branch and document it in the readme and do a check to make sure the user is running neovim before setting it. I just wanted to make sure you were open to this type of thing before I was going to send you two pull requests in a day :P

**Comment by jdkanani** [comment]
Yes of course. Go ahead.
